# Generated by Django 4.2.17 on 2025-01-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=100)),
                ('synopsis', models.TextField()),
                ('genre', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('book_cover', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('part_of_series', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('ISBN', models.CharField(max_length=20, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
