# Generated by Django 4.2.17 on 2025-01-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_book_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Featured',
            field=models.BooleanField(default=False),
        ),
    ]
