# Generated by Django 4.2.17 on 2025-01-13 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Featured',
            new_name='featured',
        ),
    ]
