# Generated by Django 4.2.17 on 2025-01-15 09:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_cover',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
