# Generated by Django 4.2.17 on 2025-01-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_rename_featured_book_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(blank=True, null=True, upload_to='book/book_covers/'),
        ),
    ]
