# Generated by Django 4.2.17 on 2025-01-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_book_approved_book_uploadedon_book_uploadedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction')], default='Fiction', max_length=20),
        ),
    ]
