# Generated by Django 4.2.17 on 2025-01-19 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_book_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
    ]
