# Generated by Django 4.2.17 on 2025-01-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
